### ISSUE TITLE
Not working with Maven & 2020.1.2

### ISSUE THREAD

**Issue by marcin-chwedczuk** [anthraxx/intellij-awesome-console#81]
Example output after running `./mvnw verify`:
```
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project card-acr122: Compilation failure: Compilation failure: 
[ERROR] /Users/mc/devel/java/rfid/app/card-acr122/src/main/java/pl/marcinchwedczuk/rfid/card/acr122/AcrCard.java:[71,64] cannot find symbol
[ERROR]   symbol:   method toHexString(byte[])
[ERROR]   location: class pl.marcinchwedczuk.rfid.card.commons.StringUtils
[ERROR] /Users/mc/devel/java/rfid/app/card-acr122/src/main/java/pl/marcinchwedczuk/rfid/card/acr122/AcrCard.java:[153,78] cannot find symbol
[ERROR]   symbol:   method toHexString(byte[])
```

None of these paths is recognized by the plugin. 

-----------
IntelliJ IDEA 2020.1.2 (Community Edition)
Build #IC-201.7846.76, built on June 1, 2020
Runtime version: 11.0.7+10-b765.53 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Non-Bundled Plugins: IdeaVIM, Key Promoter X, awesome.console, org.intellij.scala, MavenRunHelper

**Comment by dmaxddog** [comment]
Somewhere along the line the format of the line number and column number changed from something like this:

```
/Users/mc/devel/java/rfid/app/card-acr122/src/main/java/pl/marcinchwedczuk/rfid/card/acr122/AcrCard.java:71:64
```
to this:
```
/Users/mc/devel/java/rfid/app/card-acr122/src/main/java/pl/marcinchwedczuk/rfid/card/acr122/AcrCard.java:[71,64]
```
